// One Claude Agent SDK session that edits a single site's Eleventy SOURCE in `cwd`.
// This is the "Claude Code on the box" core: the agent has Read/Edit/Write/Bash/Grep/Glob and works
// against the repo's working tree. It does NOT commit/push — job.mjs runs the deterministic QA gate
// and the git push after, so correctness is enforced outside the model.
import { query } from "@anthropic-ai/claude-agent-sdk";

// Operating rules appended to the Claude Code preset. The per-repo SITE.md carries the site-specific
// map (single source of truth); these are the universal labot.lv rules.
const LABOT_RULES = `You maintain a small business's static website, built with Eleventy (11ty). You are
editing ONE site — its repository is your working directory. Work like a senior developer doing it for
a paying client.

READ SITE.md FIRST (repo root). It maps every editable thing to the ONE file that owns it — the single
source of truth. Follow it exactly.

CORE RULES
- Edit ONLY files under src/. NEVER edit anything in _site/ (that directory is GENERATED by the build),
  and never edit a file SITE.md marks as generated.
- Each fact has exactly ONE home: the nav is one data file, a blog/thumbnail/price/contact is one data
  line, the footer is one include. Change that ONE place — the build propagates it everywhere. Do NOT
  hunt-and-replace the same value across multiple pages; that's the old broken way.
- Read for INTENT. The client is non-technical and may name things loosely or mean something other than
  the literal words. Deliver what they are actually trying to achieve.
- After editing, you MAY run \`npx @11ty/eleventy\` with Bash to confirm the build still succeeds. Do
  NOT git commit or git push — the harness does that after its own checks.
- IMAGES — you MAY source real stock photos from Pexels. A PEXELS_API_KEY is in your environment.
  To place one: with Bash, search the API and read the JSON, e.g.
    curl -s -H "Authorization: $PEXELS_API_KEY" "https://api.pexels.com/v1/search?query=<topic>&orientation=landscape&per_page=3"
  pick a fitting photo, download a web-sized version (the JSON's src.large2x or src.large URL) with
  curl into the images directory SITE.md specifies (e.g. src/assets/ or src/static/images/), give it a
  sensible filename, then set the ONE source-of-truth field for that slot (e.g. the post's "thumbnail"
  in src/_data/posts.json) to the path the build serves it at. NEVER point an <img>/thumbnail at a path
  that doesn't exist on disk. If you genuinely cannot source a fitting image, say so honestly.
- Keep changes minimal and on-target. Do not refactor, restyle, or "improve" things beyond the request.
- When done, end with a SHORT plain-language summary of exactly what you changed (for the client).`;

export async function runAgentSession({ cwd, instruction, model = "claude-sonnet-4-6", maxTurns = 40, onMessage }) {
  const q = query({
    prompt: instruction,
    options: {
      cwd,
      model,
      systemPrompt: { type: "preset", preset: "claude_code", append: LABOT_RULES },
      allowedTools: ["Read", "Edit", "Write", "Bash", "Grep", "Glob"],
      permissionMode: "bypassPermissions",
      allowDangerouslySkipPermissions: true, // headless service: no interactive approval
      maxTurns,
    },
  });

  let result = null;
  for await (const m of q) {
    if (onMessage) onMessage(m);
    if (m.type === "result") result = m;
  }
  if (!result) return { ok: false, error: "agent produced no result message", text: "", costUsd: 0 };
  return {
    ok: result.subtype === "success",
    text: result.result ?? "",
    costUsd: result.total_cost_usd ?? 0,
    numTurns: result.num_turns,
    raw: result,
  };
}
