// One Claude Agent SDK session that edits a single site's Eleventy SOURCE in `cwd`.
// This is the "Claude Code on the box" core: the agent has Read/Edit/Write/Bash/Grep/Glob and works
// against the repo's working tree. It does NOT commit/push — job.mjs runs the deterministic QA gate
// and the git push after, so correctness is enforced outside the model.
import { query } from "@anthropic-ai/claude-agent-sdk";
import { statSync } from "node:fs";
import path from "node:path";

// HARD guards (spec A1/A2) — enforced via PreToolUse hooks, which still fire under
// permissionMode:"bypassPermissions" (canUseTool does NOT). These turn the prompt's "it is enforced"
// from a bluff into reality: the model physically cannot re-emit a whole file/section or slurp a huge
// file. A denied call returns its reason to the model, so it adapts (and the retry loop still applies).
const READ_MAX_BYTES = 20000; // files bigger than this MUST be read with a limit/offset slice
function deny(hookEventName, reason) {
  return { hookSpecificOutput: { hookEventName, permissionDecision: "deny", permissionDecisionReason: reason } };
}
export function buildToolGuards({ cwd, editCap }) {
  const repoRoot = path.resolve(cwd);
  const inside = (p) => {
    const abs = path.resolve(cwd, String(p || ""));
    return abs === repoRoot || abs.startsWith(repoRoot + path.sep) ? abs : null;
  };
  return async (input) => {
    const evt = input.hook_event_name; // "PreToolUse"
    const name = input.tool_name;
    const ti = input.tool_input || {};
    const fp = ti.file_path;

    // Path safety (Edit/Write/Read): never touch generated _site/, never escape the repo.
    if (fp && (name === "Edit" || name === "Write" || name === "Read")) {
      const abs = inside(fp);
      if (!abs) return deny(evt, `Path '${fp}' is outside the site repo. Only edit files inside this repository (under src/).`);
      if (abs.includes(`${path.sep}_site${path.sep}`)) return deny(evt, `'${fp}' is in _site/, which is GENERATED by the build. Edit the matching SOURCE file under src/ instead (see SITE.md).`);
    }

    // A1 — surgical edits: cap the replacement/file body so the model can't re-emit a whole section.
    if (editCap !== Infinity && (name === "Edit" || name === "Write")) {
      const body = name === "Edit" ? ti.new_string : ti.content;
      const len = (body || "").length;
      if (len > editCap) {
        return deny(evt, `${name} denied: the new content is ${len} characters; the budget for this task is ${editCap}. Make a SURGICAL edit — locate the exact text and replace only the characters that change, or split into several smaller Edits. Do not re-emit a whole section, list, or file.`);
      }
    }

    // A2 — targeted reads: a big file must be read as a slice (grep first, then read ±30 lines).
    if (name === "Read" && fp && ti.limit == null && ti.offset == null) {
      try {
        const sz = statSync(path.resolve(cwd, fp)).size;
        if (sz > READ_MAX_BYTES) {
          return deny(evt, `Read denied: '${fp}' is ${sz} bytes — too large to read whole. Grep for a stable anchor (a heading, class, id, alt text, price), then Read with offset+limit to get only the ±30 lines around it.`);
        }
      } catch { /* missing/unstattable → let the tool itself handle it */ }
    }
    return {}; // allow
  };
}

// Operating rules appended to the Claude Code preset. The per-repo SITE.md carries the site-specific
// map (single source of truth); these are the universal labot.lv rules.
const LABOT_RULES = `You maintain a small business's static website, built with Eleventy (11ty). You are
editing ONE site — its repository is your working directory. Work like a senior developer doing it for
a paying client.

READ SITE.md FIRST (repo root). It maps every editable thing to the ONE file that owns it — the single
source of truth. Follow it exactly.

CORE RULES
- Edit ONLY files under src/. NEVER edit anything in _site/ (that directory is GENERATED by the build),
  and never edit a file SITE.md marks as generated.
- Each fact has exactly ONE home: the nav is one data file, a blog/thumbnail/price/contact is one data
  line, the footer is one include. Change that ONE place — the build propagates it everywhere. Do NOT
  hunt-and-replace the same value across multiple pages; that's the old broken way.
- Read for INTENT. The client is non-technical and may name things loosely or mean something other than
  the literal words. Deliver what they are actually trying to achieve.
- After editing, you MAY run \`npx @11ty/eleventy\` with Bash to confirm the build still succeeds. Do
  NOT git commit or git push — the harness does that after its own checks.
- IMAGES — you MAY source real stock photos from Pexels. A PEXELS_API_KEY is in your environment.
  To place one: with Bash, search the API and read the JSON, e.g.
    curl -s -H "Authorization: $PEXELS_API_KEY" "https://api.pexels.com/v1/search?query=<topic>&orientation=landscape&per_page=3"
  pick a fitting photo, download a web-sized version (the JSON's src.large2x or src.large URL) with
  curl into the images directory SITE.md specifies (e.g. src/assets/ or src/static/images/), give it a
  sensible filename, then set the ONE source-of-truth field for that slot (e.g. the post's "thumbnail"
  in src/_data/posts.json) to the path the build serves it at. NEVER point an <img>/thumbnail at a path
  that doesn't exist on disk. If you genuinely cannot source a fitting image, say so honestly.
- Keep changes minimal and on-target. Do not refactor, restyle, or "improve" things beyond the request.
- TEMPLATE SAFETY: HTML comments (<!-- -->) do NOT disable Nunjucks/Liquid tags — a \`{% include %}\` or
  \`{% ... %}\` inside an HTML comment STILL executes. When you extract a block into an include, never
  leave a reference to that include inside the include itself (it self-includes → infinite recursion →
  build crash). After any template/include change, run \`npx @11ty/eleventy\` and confirm it builds before
  you finish — a change that doesn't build will be rolled back and the task counts as failed.

COST DISCIPLINE (do this — it is enforced)
- SURGICAL EDITS ONLY. Make the SMALLEST possible edit: replace only the characters that change.
  NEVER re-emit a surrounding section, list, block, or whole file. The Edit tool will REJECT a
  new_string larger than the task allows — locate the exact text and replace just that.
- TARGETED READS. Never read a large file end-to-end. Grep for a stable string (a heading, class,
  alt text, price, id), then read only the ±30 lines around it and edit from that slice. Reading a
  big file whole will be REJECTED — grep first, read the section.

FEASIBILITY (save the budget; be honest)
- If a task needs data you genuinely cannot obtain — content behind a login (e.g. scraping Instagram
  posts), third-party reviews you can't reach, an asset only the client has — do NOT thrash retrying
  for many turns. Make ONE reasonable attempt; if it won't work, STOP and state plainly what you need
  from the client (e.g. "please attach the Instagram images you want shown"). A clean hand-back in 2–3
  turns is far better than burning the whole budget and failing.

VERIFICATION (REQUIRED — you cannot be marked "done" without it)
- A human is NOT watching. Before anything ships, a browser/HTTP check confirms your change is live
  and correct. You MUST tell that checker how to prove your work. End your reply with a single block:
    <VERIFY>
    [ {"page":"/<path-as-served>","contains":"<an exact unique string that should now be live>"} ,
      {"page":"/<path>","interaction":{"click":"<CSS selector>","expectVisible":"<sel>","expectHidden":"<sel>"}} ]
    </VERIFY>
  - One entry per change. \`page\` is the deployed URL path (e.g. "/", "/pages/uznemumiem/").
  - For a TEXT/content change: give a \`contains\` string that is unique and now present on the page.
  - For an INTERACTIVE change (toggle/form/carousel/JS): give an \`interaction\` the checker can run
    (click a selector, assert another element becomes visible/hidden). If you truly cannot name a
    check for an interactive edit, say so plainly in your summary and DO NOT imply it is verified.
  - Never claim something works that you have not made checkable. Honesty over completeness.
- When done, end with a SHORT plain-language summary of exactly what you changed (for the client),
  immediately followed by the <VERIFY> block.`;

export async function runAgentSession({ cwd, instruction, model = "claude-sonnet-4-6", maxTurns = 40, editCap = Infinity, onMessage }) {
  const guard = buildToolGuards({ cwd, editCap });
  const q = query({
    prompt: instruction,
    options: {
      cwd,
      model,
      systemPrompt: { type: "preset", preset: "claude_code", append: LABOT_RULES },
      allowedTools: ["Read", "Edit", "Write", "Bash", "Grep", "Glob"],
      permissionMode: "bypassPermissions",
      allowDangerouslySkipPermissions: true, // headless service: no interactive approval
      hooks: { PreToolUse: [{ matcher: "Read|Edit|Write", hooks: [guard] }] },
      maxTurns,
    },
  });

  // Accumulate usage from the stream so we have per-task telemetry EVEN when the SDK throws on
  // max_turns (it throws before emitting a result message). Output tokens sum across turns; input/cache
  // are cumulative-context, so we keep the max seen. On a clean finish the result message's exact
  // totals + total_cost_usd win; on a throw we fall back to this accumulator with an estimated cost.
  const acc = { input_tokens: 0, output_tokens: 0, cache_read_input_tokens: 0, cache_creation_input_tokens: 0 };
  let result = null, turnsSeen = 0, thrown = null;
  try {
    for await (const m of q) {
      if (onMessage) onMessage(m);
      const u = m.type === "assistant" ? m.message?.usage : null;
      if (u) {
        acc.output_tokens += u.output_tokens || 0;
        acc.input_tokens = Math.max(acc.input_tokens, u.input_tokens || 0);
        acc.cache_read_input_tokens = Math.max(acc.cache_read_input_tokens, u.cache_read_input_tokens || 0);
        acc.cache_creation_input_tokens = Math.max(acc.cache_creation_input_tokens, u.cache_creation_input_tokens || 0);
        turnsSeen++;
      }
      if (m.type === "result") result = m;
    }
  } catch (e) {
    thrown = e; // typically "Reached maximum number of turns (N)"
  }
  if (result) {
    return { ok: result.subtype === "success", text: result.result ?? "", costUsd: result.total_cost_usd ?? 0, numTurns: result.num_turns, raw: result };
  }
  // No result message → SDK threw (e.g. max_turns). Return structured failure WITH best-effort usage.
  const maxedOut = /maximum number of turns/i.test(String(thrown || ""));
  return {
    ok: false,
    error: thrown ? String(thrown) : "agent produced no result message",
    text: "",
    costUsd: estimateCost(model, acc),
    numTurns: turnsSeen,
    raw: { usage: acc, estimated: true, maxedOut },
  };
}

// Rough per-task cost estimate (USD) from token counts, for the max_turns case where the SDK gives no
// total_cost_usd. Prices are per million tokens; cache_read ≈0.1× input, cache_write ≈1.25× input.
const PRICES = [
  { m: "haiku", in: 1, out: 5 },
  { m: "sonnet", in: 3, out: 15 },
  { m: "opus", in: 15, out: 75 },
];
function estimateCost(model, u) {
  const p = PRICES.find((x) => String(model || "").includes(x.m)) || PRICES[1];
  return (
    (u.input_tokens * p.in + u.output_tokens * p.out + u.cache_read_input_tokens * p.in * 0.1 + u.cache_creation_input_tokens * p.in * 1.25) / 1e6
  );
}
